PharmaMG/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from app_account.views import home_view, business_login, business_logout, register_user_ajax, \
    patient_login, patient_logout

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home_view, name="home"),
    path('bui_login/', business_login, name="bui_login"),
    path('bui_logout/', business_logout, name="bui_logout"),

    path('register_user_ajax/', register_user_ajax, name="send_otp"),
    path('patient_login/', patient_login, name="patient_login"),
    path('patient_logout/', patient_logout, name="patient_logout"),

    path('pharma-mg/', include(('app_pharma_mg.urls', 'app_pharma_mg'), namespace='pharmamg')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_pharma_mg/urls.py
from django.urls import path

from app_pharma_mg import cart_views
from app_pharma_mg.cart_views import order_detail
from app_pharma_mg.views import *

urlpatterns = [
    # BUI urls
    path('bui_dashboard/', dashboard_view, name="dashboard"),

    # pharmacy urls for admin user
    path('bui_manage_pharmacy/', manage_pharmacy_view, name="manage_pharmacy"),
    path('bui_add_pharmacy/', add_pharmacy, name="add_pharmacy"),
    path('edit_form_ajax/', edit_form_ajax, name="edit_form_ajax"),
    path('bui_delete_pharmacy/<str:pharmacy_id>/', delete_pharmacy_ajax, name="delete_pharmacy"),

    # clinic urls for admin user
    path('bui_manage_clinic/', manage_clinic_view, name="manage_clinic"),
    path('bui_add_clinic/', add_clinic, name="add_clinic"),
    path('edit_clinic_form_ajax/', edit_form_ajax, name="edit_clinic_form_ajax"),
    path('bui_delete_clinic/<str:clinic_id>/', delete_pharmacy_ajax, name="delete_clinic"),

    # PHARMACY USER urls
    path('bui_pharmacy_dashboard/', dashboard_pharmacy_view, name="pharmacy_dashboard"),
    path('bui_pharmacy_users/', manage_pharmacy_user_view, name="manage_pharmacy_users"),
    path('bui_pharmacy_users_delete/<str:user_id>/', delete_pharmacy_employee_ajax, name="delete_pharmacy_employee"),
    path('bui_add_pharmacy_user/', add_pharmacy_employee, name="add_pharmacy_employee"),
    path('bui_pharmacy_products/', manage_pharmacy_products_view, name="manage_pharmacy_products"),
    path('bui_pharmacy_edit_product_form_ajax/', edit_product_form_ajax, name="edit_product_form_ajax"),
    path('bui_add_pharmacy_product/', add_pharmacy_product, name="add_pharmacy_product"),
    path('bui_create_order_pharmacy_view/', create_order_pharmacy_view, name="create_order_pharmacy_view"),
    path('bui_create_order_ajax/', create_order_ajax, name="create_order_ajax"),
    path('bui_manage_pharmacy_orders_view/', manage_pharmacy_orders_view, name="manage_pharmacy_orders_view"),

    # CLINIC USER urls
    path('bui_clinic_dashboard/', dashboard_clinic_view, name="clinic_dashboard"),
    path('bui_clinic_users/', manage_clinic_user_view, name="manage_clinic_users"),
    path('bui_clinic_users_delete/<str:user_id>/', delete_clinic_employee_ajax, name="delete_clinic_employee"),
    path('bui_add_clinic_user/', add_clinic_employee, name="add_clinic_employee"),
    path('bui_schedule_consultation_view/', schedule_consultation_view, name="schedule_consultation_view"),
    path('bui_schedule_consultation_ajax/', schedule_consultation_ajax, name="schedule_consultation_ajax"),
    path('bui_manage_consultation_view/', manage_consultation_view, name="manage_consultation_view"),

    # PATIENT/CUSTOMER urls
    path('patient_home/', patient_home, name="patient_home"),
    path('order_detail/', order_detail, name="order_detail"),

    # CART URLS
    path('cart/add/<str:id>/', cart_views.cart_add, name='cart_add'),
    path('cart/item_clear/<str:id>/', cart_views.item_clear, name='item_clear'),
    path('cart/item_increment/<str:id>/',
         cart_views.item_increment, name='item_increment'),
    path('cart/item_decrement/<str:id>/',
         cart_views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', cart_views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/', cart_views.cart_detail, name='cart_detail'),
    path('cart/checkout/', cart_views.checkout, name='checkout'),

]

app_pharma_mg/models.py
import uuid

from django.db import models

from app_account.models import Profile

TIMINGS = (
    ('9-6', (
        ('9-10', '9 am to 10 am'),
        ('10-11', '10 am to 11 am'),
        ('11-12', '11 am to 12 pm'),
        ('12-13', '12 pm to 1 pm'),
        ('14-15', '2 pm to 3 pm'),
        ('14-15', '2 pm to 3 pm'),
        ('15-16', '3 pm to 4 pm'),
        ('16-17', '4 pm to 5 pm'),
    )),
    ('9-8', (
        ('9-10', '9 am to 10 am'),
        ('10-11', '10 am to 11 am'),
        ('11-12', '11 am to 12 pm'),
        ('12-13', '12 pm to 1 pm'),
        ('14-15', '2 pm to 3 pm'),
        ('14-15', '2 pm to 3 pm'),
        ('15-16', '3 pm to 4 pm'),
        ('16-17', '4 pm to 5 pm'),
        ('17-18', '5 pm to 6 pm'),
    )),
    ('12-8', (
        ('12-13', '12 pm to 1 pm'),
        ('14-15', '2 pm to 3 pm'),
        ('14-15', '2 pm to 3 pm'),
        ('15-16', '3 pm to 4 pm'),
        ('16-17', '4 pm to 5 pm'),
        ('17-18', '5 pm to 6 pm'),
    )),
    ('12-10', (
        ('12-13', '12 pm to 1 pm'),
        ('14-15', '2 pm to 3 pm'),
        ('14-15', '2 pm to 3 pm'),
        ('15-16', '3 pm to 4 pm'),
        ('16-17', '4 pm to 5 pm'),
        ('17-18', '5 pm to 6 pm'),
        ('18-19', '6 pm to 7 pm'),
        ('19-20', '7 pm to 8 pm'),
        ('20-21', '8 pm to 9 pm'),
    )),
)


class Pharmacy(models.Model):
    pid = models.UUIDField(primary_key=True, default=uuid.uuid4)
    added_by = models.ForeignKey(Profile, on_delete=models.CASCADE)

    name = models.CharField(blank=True, null=True, max_length=200)
    address = models.TextField(blank=True, null=True)

    store_phone = models.CharField(blank=True, null=True, max_length=15)
    store_additional_contact = models.CharField(blank=True, null=True, max_length=15)
    email = models.CharField(blank=True, null=True, max_length=200)

    registration_certificates = models.FileField(blank=True, null=True)

    is_verified = models.BooleanField(default=False)
    is_phone_verified = models.BooleanField(default=False)

    gst_registration_number = models.CharField(blank=True, null=True, max_length=150)

    date_of_establishment = models.DateField(blank=True, null=True)

    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_time',)

    def __str__(self):
        return f"{self.pid}"


class PharmacyUsers(models.Model):
    USERS = (
        ('owner', 'Store Owner'),
        ('pharmacist', 'Pharmacist'),
    )

    pharmacy_user_id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.OneToOneField(Profile, on_delete=models.CASCADE)

    pharmacy = models.ForeignKey(Pharmacy, on_delete=models.CASCADE, blank=True, null=True)

    role = models.CharField(blank=True, null=True, choices=USERS, max_length=200)

    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_time',)

    def __str__(self):
        return f"{self.pharmacy_user_id}"


class Clinic(models.Model):
    TIMINGS = (
        ('9-6', '9 am to 6 pm'),
        ('9-8', '9 am to 8 pm'),
        ('12-8', '12 am to 8 pm'),
        ('12-10', '12 am to 10 pm'),
    )

    cid = models.UUIDField(primary_key=True, default=uuid.uuid4)
    added_by = models.ForeignKey(Profile, on_delete=models.CASCADE)

    name = models.CharField(blank=True, null=True, max_length=200)
    address = models.TextField(blank=True, null=True)

    type_of_clinic = models.CharField(blank=True, null=True, max_length=100)
    clinic_timing = models.CharField(blank=True, null=True, max_length=100, choices=TIMINGS)

    registered_phone = models.CharField(blank=True, null=True, max_length=15)
    additional_contact = models.CharField(blank=True, null=True, max_length=15)
    email = models.CharField(blank=True, null=True, max_length=200)

    registration_certificates = models.FileField(blank=True, null=True)

    is_verified = models.BooleanField(default=False)
    is_phone_verified = models.BooleanField(default=False)

    gst_registration_number = models.CharField(blank=True, null=True, max_length=150)

    date_of_establishment = models.DateField(blank=True, null=True)

    updated_on = models.DateTimeField(auto_now=True)
    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_time',)

    def __str__(self):
        return f"{self.cid}"


class ClinicUsers(models.Model):
    USERS = (
        ('doctor', 'Doctor'),
        ('reciptionist', 'Reciptionist'),
    )

    clinic_user_id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.OneToOneField(Profile, on_delete=models.CASCADE)

    clinic = models.ForeignKey(Clinic, on_delete=models.CASCADE, blank=True, null=True)
    specialization = models.CharField(blank=True, null=True, max_length=200)

    role = models.CharField(blank=True, null=True, choices=USERS, max_length=200)

    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_time',)

    def __str__(self):
        return f"{self.clinic_user_id}"


def product_id_create():
    return "PR_" + uuid.uuid4()


class Item(models.Model):
    CATEGORY = (
        ('drugs', 'DRUG'),
        ('antibiotic', 'ANIT-BIOTICS'),
        ('syrup', 'SYRUP'),
        ('allopathy', 'ALLOPATHY'),
        ('homeopathy', 'HOMEOPATHY'),
        ('vitamins_supplements', 'VITAMINS and SUPPLEMENTS'),
        ('personal_care', 'PERSONAL CARE'),
        ('protein', 'PROTEIN SUPPLEMENTS'),
    )

    item_id = models.CharField(primary_key=True, default=product_id_create, max_length=200)
    pharmacy = models.ForeignKey(Pharmacy, on_delete=models.CASCADE, blank=True, null=True)

    item_name = models.CharField(blank=True, null=True, max_length=200)
    item_category = models.CharField(blank=True, null=True, choices=CATEGORY, max_length=200)
    item_price = models.FloatField(blank=True, null=True)
    item_stock = models.IntegerField(blank=True, null=True)
    item_composition = models.CharField(blank=True, null=True, max_length=200)
    item_dose = models.CharField(blank=True, null=True, max_length=200)
    item_uses = models.TextField(blank=True, null=True)
    item_side_effects = models.TextField(blank=True, null=True)

    item_brand = models.CharField(blank=True, null=True, max_length=200)
    item_manufacturer = models.CharField(blank=True, null=True, max_length=200)
    item_information = models.TextField(blank=True, null=True)

    item_image = models.FileField(blank=True, null=True)

    is_prescription_required = models.BooleanField(default=False)

    updated_on = models.DateTimeField(auto_now=True)
    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_time', '-updated_on')

    def __str__(self):
        return f"{self.item_name}"


class Prescription(models.Model):
    prescription_id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    added_by = models.ForeignKey(Profile, on_delete=models.CASCADE)

    prescription_name = models.CharField(blank=True, null=True, max_length=200)
    prescribed_by = models.CharField(blank=True, null=True, max_length=200)

    prescription = models.FileField(blank=True, null=True)

    order_updated_on = models.DateTimeField(auto_now=True)
    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_time', '-order_updated_on')

    def __str__(self):
        return f"{self.prescription_name}"


class Transaction(models.Model):
    STATUS = (
        ('success', 'SUCCESS'),
        ('incomplete', 'ON HOLD'),
        ('failed', 'FAILED'),
        ('rollbacked', 'ROLLBACKED'),
    )

    transaction_id = models.UUIDField(primary_key=True, default=uuid.uuid4)

    transaction_status = models.CharField(blank=True, null=True, choices=STATUS, max_length=50)
    transaction_mode = models.CharField(blank=True, null=True, max_length=50)

    order_updated_on = models.DateTimeField(auto_now=True)
    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_time', '-order_updated_on')

    def __str__(self):
        return f"{self.transaction_id}"


class Order(models.Model):
    MODE = (
        ('online', 'ONLINE'),
        ('offline', 'STORE POS'),
        ('oncall', 'ON CALL ORDER'),
    )

    STATUS = (
        ('placed', 'ORDER PLACED'),
        ('packed', 'ORDER PACKED'),
        ('delivery', 'OUT FOR DELIVERY'),
        ('delivered', 'DELIVERED'),
    )

    order_id = models.UUIDField(primary_key=True, default=uuid.uuid4)

    placed_by = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, null=True)
    store = models.ForeignKey(Pharmacy, on_delete=models.CASCADE, blank=True, null=True)
    item = models.ManyToManyField(Item, blank=True)
    transaction = models.OneToOneField(Transaction, on_delete=models.CASCADE, blank=True, null=True)

    prescription = models.ManyToManyField(Prescription, blank=True)

    total_amount = models.FloatField(blank=True, null=True)

    mode = models.CharField(blank=True, null=True, choices=MODE, default="offline", max_length=100)
    order_status = models.CharField(blank=True, null=True, choices=STATUS, max_length=100)

    order_updated_on = models.DateTimeField(auto_now=True)
    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_time', '-order_updated_on')

    def __str__(self):
        return f"{self.order_id}"


class Consultation(models.Model):
    MODE = (
        ('online', 'ONLINE'),
        ('offline', 'CLINIC VISIT'),
        ('oncall', 'ON CALL'),
    )

    STATUS = (
        ('canceled', 'CANCELED'),
        ('rescheduled', 'RESCHUDLED'),
        ('booked', 'BOOKED'),
        ('ongoing', 'ONGOING'),
        ('completed', 'COMPLETED'),
    )

    consultation_id = models.UUIDField(primary_key=True, default=uuid.uuid4)

    placed_by = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, null=True)

templates/app_pharma_mg/bui/html/clinic/add_employee.html
{% extends "app_pharma_mg/bui/html/main.html" %}
{% load static %}

{% block main_block %}
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-user-plus me-1"></i>
        Add Employee
    </div>
    <div class="card-body">
        {% include 'snippets/alerts/form_alerts.html' %}
        <form class="px-3 py-4 text-center" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            {% if field.label != "Profile pic" %}
            <div class="form-group row my-4">
                <label class="form-label col-sm-4"
                       for="{{ field.auto_id }}">{{ field.label }}</label>
                <div class="col-sm-8">
                    {{ field }}
                </div>
            </div>
            {% else %}
            <div class="mb-3 my-4 row">
                <label class="form-label col-sm-4" for="{{ field.auto_id }}">{{ field.label }}</label>
                <div class="col-sm-8">
                    {{ field }}
                </div>
            </div>
            {% endif %}
            {% endfor %}
            <button class="w-40 btn btn-lg btn-primary my-4" type="submit">Add User</button>
        </form>
    </div>
</div>
{% endblock %}

templates/app_pharma_mg/bui/html/clinic/create_appointments.html
{% extends "app_pharma_mg/bui/html/main.html" %}
{% load static %}

{% block main_block %}
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-user-plus me-1"></i>
        Create Appointment
    </div>
    <div class="card-body">
        {% include 'snippets/alerts/form_alerts.html' %}
        <form class="px-3 py-4 text-center" id="appointment_form" name="createAppointmentForm" method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3 my-4 row">
                <label class="form-label col-sm-4 col-form-label control-label" for="formSelectMode">Payment
                    Status</label>
                <div class="col-sm-8">
                    <select name="mode" class="form-select" id="formSelectMode" required>
                        <option value="offline">CLINIC VISIT</option>
                        <option value="oncall">ON CALL</option>
                    </select>
                </div>
            </div>
            <div class="form-group row my-4">
                <label class="col-sm-4 col-form-label " for="id_patient_mobile">Patient Mobile</label>
                <div class="col-sm-8">
                    <input type="number" name="patient_mobile" class="form-control" maxlength="10" minlength="10"
                           id="id_patient_mobile" required>
                </div>
            </div>
            <div class="form-group row my-4">
                <label class="col-sm-4 col-form-label " for="id_patient_name">Patient Name</label>
                <div class="col-sm-8">
                    <input type="text" name="patient_name" class="form-control" maxlength="150" id="id_patient_name">
                </div>
            </div>
            <div class="form-group row my-4">
                <label class="col-sm-4 col-form-label " for="id_patient_address">Patient Address</label>
                <div class="col-sm-8">
                    <textarea name="patient_address" cols="40" rows="10" class="form-control" required=""
                              id="id_patient_address"></textarea>
                </div>
            </div>

            <div class="mb-3 my-4 row">
                <label for="formSelectDate" class="form-label col-sm-4 col-form-label control-label">Appointment
                    Date</label>
                <div class="col-sm-8">
                    <div class="input-group date" id="datepicker">
                        <input type="text" class="form-control" id="formSelectDate" name="appointment_date"/>
                        <span class="input-group-append">
                      <span class="input-group-text bg-light d-block">
                        <i class="fa fa-calendar"></i>
                      </span>
                    </span>
                    </div>
                </div>
            </div>

            <div class="mb-3 my-4 row">
                <label class="form-label col-sm-4 col-form-label control-label" for="formSelectTime">Appointment
                    Time</label>
                <div class="col-sm-8">
                    <select name="appointment_time" class="form-select" id="formSelectTime" required>
                        {% for key,val in timings.items %}
                        <option value="{{key}}">{{val}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="form-group row my-4">
                <label class="col-sm-4 col-form-label " for="id_consultation_charge">Consultation Charge</label>
                <div class="col-sm-8">
                    <input type="number" name="consultation_charge" class="form-control" maxlength="150"
                           id="id_consultation_charge">
                </div>
            </div>

            <div class="mb-3 my-4 row">
                <label class="form-label col-sm-4 col-form-label control-label" for="formSelectPaymentStatus">Payment
                    Status</label>
                <div class="col-sm-8">
                    <select name="payment_status" class="form-select" id="formSelectPaymentStatus" required>
                        <option value="success">RECIEVED</option>
                        <option value="incomplete">HOLD</option>
                    </select>
                </div>
            </div>
            <div class="mb-3 my-4 row">
                <label class="form-label col-sm-4 col-form-label control-label" for="formSelectPaymentMode">Payment
                    Mode</label>
                <div class="col-sm-8">
                    <select name="payment_mode" class="form-select" id="formSelectPaymentMode" required>
                        <option value="cash">CASH</option>
                        <option value="card">CARD</option>
                        <option value="upi">UPI</option>
                    </select>
                </div>
            </div>
            <button class="w-40 btn btn-lg btn-primary my-4" type="submit">Create</button>
        </form>
    </div>
</div>
{% endblock %}

{% block extra_js %}
{% include 'app_pharma_mg/bui/js/clinic/create_appointment.js' %}
{% endblock %}

templates/app_pharma_mg/bui/html/clinic/dashboard_clinic.html
{% extends "app_pharma_mg/bui/html/main.html" %}
{% load static %}

{% block main_block %}
<h1 class="mt-4">Dashboard</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Dashboard</li>
</ol>
<div class="row">
    <div class="col-xl-6 col-md-6">
        <div class="card bg-white text-dark mb-4 text-center">
            <div class="card-body fw-bold lh-sm">
                <span class="fs-1">{{consultation_get_qs|length}}</span>
                <hr class="dropdown-divider"/>
                Consultations Done
            </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-dark stretched-link"
                   href="{% url 'pharmamg:manage_consultation_view' %}">Manage</a>
                <div class="small text-dark"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    {% if clinic_user_get_qs.role == 'doctor' %}
    <div class="col-xl-6 col-md-6">
        <div class="card bg-white text-dark mb-4 text-center">
            <div class="card-body fw-bold lh-sm">
                <span class="fs-1">{{clinic_users_filter_qs|length}}</span>
                <hr class="dropdown-divider"/>
                Employees Working
            </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-dark stretched-link" href="{% url 'pharmamg:manage_clinic_users' %}">Manage</a>
                <div class="small text-dark"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/app_pharma_mg/bui/html/clinic/manage_appointments.html
{% extends "app_pharma_mg/bui/html/main.html" %}
{% load static %}

{% block main_block %}
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        Manage Appointments
    </div>
    <div class="card-body">
        <table id="datatablesSimple" class="display responsive" width="100%">
            <thead>
            <tr>
                <th>PATIENT</th>
                <th>DATE</th>
                <th>TIME</th>
                <th>MODE</th>
                <th>STATUS</th>
                <th>CHARGE</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% include 'app_pharma_mg/bui/html/clinic/partial_manage_appointments.html' %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block extra_js %}
{% include 'app_pharma_mg/bui/js/pharmacy/manage_item.js' %}
{% endblock %}

templates/app_pharma_mg/bui/html/clinic/manage_employee.html
{% extends "app_pharma_mg/bui/html/main.html" %}
{% load static %}

{% block main_block %}
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        Manage Pharmacy
    </div>
    <div class="card-body">
        <table id="datatablesSimple" class="display responsive" width="100%">
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Mobile</th>
                <th>Role</th>
                <th>Specialization</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% include 'app_pharma_mg/bui/html/clinic/partial_manage_employee.html' %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block extra_js %}
{% endblock %}

templates/app_pharma_mg/bui/html/clinic/partial_manage_appointments.html
{% for appointment in consultation_filter_qs %}
<tr>
    <td>{{appointment.placed_by.first_name|title}} {{appointment.placed_by.last_name|title}}</td>
    <td>{{appointment.appointment_date}}</td>
    <td>{{appointment.appointment_time}}</td>
    <td>{{appointment.mode}}</td>
    <td>{{appointment.status}}</td>
    <td>Rs. {{appointment.total_amount}}</td>
    <td>
        <ul class="list-group list-group-horizontal">
            <li class="list-group-item">
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-outline-primary edit" data-bs-toggle="modal"
                        data-bs-target="#editProduct" onload="editData('{{product.item_id}}')">
                    <i class="fas fa-edit" aria-hidden="true"></i>
                </button>

                <div class="modal fade" id="editProduct" tabindex="-1" aria-labelledby="exampleModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="exampleModalLabel">Edit</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                {% include 'snippets/alerts/form_alerts.html' %}
                                <form class="px-3 py-4 text-center editForm" name="editProductForm"
                                      action="javascript:void(0)" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-group row my-4">
                                        <label class="col-sm-4 col-form-label " for="id_item_id">Product ID</label>
                                        <div class="col-sm-8">
                                            <input type="text" name="item_id" value="{{appointment.consultation_id}}"
                                                   class="form-control" maxlength="200" disabled id="id_item_id">
                                        </div>
                                    </div>
                                    <div class="mb-3 my-4 row">
                                        <label class="form-label col-sm-4 col-form-label " for="id_item_image">Product
                                            Image</label>
                                        <div class="col-sm-8">
                                            <input type="file" name="item_image" class="form-control"
                                                   help_text="Upload Product Image" id="id_item_image">
                                        </div>
                                    </div>
                                    <div class="form-group row my-4">
                                        <label class="col-sm-4 col-form-label " for="id_stock">Update Stock</label>
                                        <div class="col-sm-8">
                                            <input type="number" name="item_stock" class="form-control" maxlength="5"
                                                   id="id_stock">
                                        </div>
                                    </div>
                                    <button class="w-40 btn btn-lg btn-primary my-4" type="submit">Save Changes</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </td>
</tr>
{% endfor %}

templates/app_pharma_mg/bui/html/clinic/partial_manage_employee.html
{% for employee in clinic_users_filter_qs %}
<tr>
    <td>{{employee.clinic_user_id}}</td>
    <td>{{employee.user.first_name|title}} {{pharmacy.user.last_name|title}}</td>
    <td>{{employee.user.phone}}</td>
    <td>{{employee.role|title}}</td>
    <td>{{employee.specialization|title}}</td>
    <td>
        <ul class="list-group list-group-horizontal">
            <li class="list-group-item">
                <a type="button" class="btn btn-outline-danger delete"
                   href="{% url 'pharmamg:delete_clinic_employee' user_id=employee.clinic_user_id %}"><i
                        class="fas fa-trash bg-outline-danger" aria-hidden="true"></i></a>
            </li>
        </ul>
    </td>
</tr>
{% endfor %}