PharmaMG/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from app_account.views import home_view, business_login, business_logout, register_user_ajax, \
    patient_login, patient_logout

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home_view, name="home"),
    path('bui_login/', business_login, name="bui_login"),
    path('bui_logout/', business_logout, name="bui_logout"),

    path('register_user_ajax/', register_user_ajax, name="send_otp"),
    path('patient_login/', patient_login, name="patient_login"),
    path('patient_logout/', patient_logout, name="patient_logout"),

    path('pharma-mg/', include(('app_pharma_mg.urls', 'app_pharma_mg'), namespace='pharmamg')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_pharma_mg/urls.py
from django.urls import path

from app_pharma_mg import cart_views
from app_pharma_mg.cart_views import order_detail
from app_pharma_mg.views import *

urlpatterns = [
    # BUI urls
    path('bui_dashboard/', dashboard_view, name="dashboard"),

    # pharmacy urls for admin user
    path('bui_manage_pharmacy/', manage_pharmacy_view, name="manage_pharmacy"),
    path('bui_add_pharmacy/', add_pharmacy, name="add_pharmacy"),
    path('edit_form_ajax/', edit_form_ajax, name="edit_form_ajax"),
    path('bui_delete_pharmacy/<str:pharmacy_id>/', delete_pharmacy_ajax, name="delete_pharmacy"),

    # clinic urls for admin user
    path('bui_manage_clinic/', manage_clinic_view, name="manage_clinic"),
    path('bui_add_clinic/', add_clinic, name="add_clinic"),
    path('edit_clinic_form_ajax/', edit_form_ajax, name="edit_clinic_form_ajax"),
    path('bui_delete_clinic/<str:clinic_id>/', delete_pharmacy_ajax, name="delete_clinic"),

    # PHARMACY USER urls
    path('bui_pharmacy_dashboard/', dashboard_pharmacy_view, name="pharmacy_dashboard"),
    path('bui_pharmacy_users/', manage_pharmacy_user_view, name="manage_pharmacy_users"),
    path('bui_pharmacy_users_delete/<str:user_id>/', delete_pharmacy_employee_ajax, name="delete_pharmacy_employee"),
    path('bui_add_pharmacy_user/', add_pharmacy_employee, name="add_pharmacy_employee"),
    path('bui_pharmacy_products/', manage_pharmacy_products_view, name="manage_pharmacy_products"),
    path('bui_pharmacy_edit_product_form_ajax/', edit_product_form_ajax, name="edit_product_form_ajax"),
    path('bui_add_pharmacy_product/', add_pharmacy_product, name="add_pharmacy_product"),
    path('bui_create_order_pharmacy_view/', create_order_pharmacy_view, name="create_order_pharmacy_view"),
    path('bui_create_order_ajax/', create_order_ajax, name="create_order_ajax"),
    path('bui_manage_pharmacy_orders_view/', manage_pharmacy_orders_view, name="manage_pharmacy_orders_view"),

    # CLINIC USER urls
    path('bui_clinic_dashboard/', dashboard_clinic_view, name="clinic_dashboard"),
    path('bui_clinic_users/', manage_clinic_user_view, name="manage_clinic_users"),
    path('bui_clinic_users_delete/<str:user_id>/', delete_clinic_employee_ajax, name="delete_clinic_employee"),
    path('bui_add_clinic_user/', add_clinic_employee, name="add_clinic_employee"),
    path('bui_schedule_consultation_view/', schedule_consultation_view, name="schedule_consultation_view"),
    path('bui_schedule_consultation_ajax/', schedule_consultation_ajax, name="schedule_consultation_ajax"),
    path('bui_manage_consultation_view/', manage_consultation_view, name="manage_consultation_view"),

    # PATIENT/CUSTOMER urls
    path('patient_home/', patient_home, name="patient_home"),
    path('order_detail/', order_detail, name="order_detail"),

    # CART URLS
    path('cart/add/<str:id>/', cart_views.cart_add, name='cart_add'),
    path('cart/item_clear/<str:id>/', cart_views.item_clear, name='item_clear'),
    path('cart/item_increment/<str:id>/',
         cart_views.item_increment, name='item_increment'),
    path('cart/item_decrement/<str:id>/',
         cart_views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', cart_views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/', cart_views.cart_detail, name='cart_detail'),
    path('cart/checkout/', cart_views.checkout, name='checkout'),

]

app_pharma_mg/views.py
import logging as log_print
import random

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect

from app_account.models import Profile
from app_account.src.utils import generate_random_user, generate_random_patient_user
from app_pharma_mg.forms import NewPharmacyRegistrationForm, NewPharmacyEmployeeForm, NewClinicRegistrationForm, \
    AddProductForm, NewClinicEmployeeForm
from app_pharma_mg.models import Pharmacy, PharmacyUsers, Clinic, ClinicUsers, Order, Item, Transaction, Consultation, \
    TIMINGS


def setup_custom_logger(name):
    formatter = log_print.Formatter(fmt='%(asctime)s - %(process)d - %(levelname)s - %(message)s')
    fh = log_print.FileHandler(settings.LOGS_DIR / 'app_pharma_mg.out')
    fh.setFormatter(formatter)
    logger = log_print.getLogger(name)
    logger.setLevel(log_print.INFO)
    logger.addHandler(fh)
    return logger


logger = setup_custom_logger("app_pharma_mg")

"""
###############################################
            ADMIN VIEWS
        --------------------
               START
###############################################
"""


@login_required
def dashboard_view(request):
    template = "app_pharma_mg/bui/html/dashboard.html"

    profile_get_qs = get_object_or_404(Profile, user=request.user)
    pharmacy_get_qs = Pharmacy.objects.all()
    clinic_get_qs = Clinic.objects.all()

    context_payload = {
        "profile_get_qs": profile_get_qs,
        "pharmacy_get_qs": pharmacy_get_qs,
        "clinic_get_qs": clinic_get_qs
    }
    return render(request=request, template_name=template, context=context_payload)


"""     PHARMACY      """


@login_required
def manage_pharmacy_view(request):
    template = "app_pharma_mg/bui/html/manage_pharmacy.html"

    profile_get_qs = get_object_or_404(Profile, user=request.user)
    pharmacy_get_qs = Pharmacy.objects.all()
    pharmacy_user_get_qs = PharmacyUsers.objects.filter(pharmacy__in=pharmacy_get_qs)

    context_payload = {
        "profile_get_qs": profile_get_qs,
        "pharmacy_user_get_qs": pharmacy_user_get_qs
    }
    return render(request=request, template_name=template, context=context_payload)


@login_required
def add_pharmacy(request):
    template = "app_pharma_mg/bui/html/add_pharmacy.html"
    profile_get_qs = Profile.objects.get(user=request.user)
    if request.method == "POST":
        form = NewPharmacyRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            form_cleaned_data = form.cleaned_data
            name = form_cleaned_data['name']
            email = form_cleaned_data['email']
            store_phone = form_cleaned_data['store_phone']
            store_additional_contact = form_cleaned_data['store_additional_contact']
            address = form_cleaned_data['address']
            registration_certificates = form_cleaned_data['registration_certificates']
            is_verified = form_cleaned_data['is_verified']
            is_phone_verified = form_cleaned_data['is_phone_verified']
            gst_registration_number = form_cleaned_data['gst_registration_number']
            date_of_establishment = form_cleaned_data['date_of_establishment']

            pharmacy_create_qs = Pharmacy.objects.create(
                added_by=profile_get_qs,
                name=name,
                email=email,
                store_phone=store_phone,
                store_additional_contact=store_additional_contact,
                address=address,
                registration_certificates=registration_certificates,
                is_verified=is_verified,
                is_phone_verified=is_phone_verified,
                gst_registration_number=gst_registration_number,
                date_of_establishment=date_of_establishment,
            )

            # Owner create for Pharmacy
            username = f"{name.replace(' ', '_').lower()}__{pharmacy_create_qs.pk}__owner"
            owner = generate_random_user(username, first_name=f"Pharmacy_{pharmacy_create_qs.pk}", last_name="Owner",
                                         email=email, phone=store_phone)

            profile_create_qs = Profile.objects.create(
                user=owner,
                role="pharmacist",
                first_name=f"Pharmacy_{pharmacy_create_qs.pk}",
                last_name="Owner",
                email=email,
                phone=store_phone
            )

            phar_user_create_qs = PharmacyUsers.objects.create(
                user=profile_create_qs,
                pharmacy=pharmacy_create_qs,
                role="owner",
            )

            return redirect('pharmamg:manage_pharmacy')
    else:
        form = NewPharmacyRegistrationForm()

    context_payload = {"form": form, "profile_get_qs": profile_get_qs}
    return render(request=request, template_name=template, context=context_payload)


@login_required
def delete_pharmacy_ajax(request, pharmacy_id: str):
    print('request.api_url---', request.api_url)

    try:
        pharmacy_get_qs = get_object_or_404(Pharmacy, pk=pharmacy_id)
    except:
        logger.exception("Delete Pharmacy Exception: ")
    else:
        pharmacy_get_qs.delete()

    return redirect("pharmamg:manage_pharmacy")


@login_required
def edit_form_ajax(request):
    status = "failure"
    message = "Invalid ID"

    if request.method == "POST":
        pharmacy_id = request.POST.get('pharmacy_id')
        try:
            pharmacy_get_qs = Pharmacy.objects.get(pk=pharmacy_id)
        except:
            message = "Invalid Pharmacy ID"
        else:
            pharmacy_get_qs.name = request.POST.get('name', pharmacy_get_qs.name)
            pharmacy_get_qs.address = request.POST.get('address', pharmacy_get_qs.address)
            pharmacy_get_qs.store_phone = request.POST.get('store_phone', pharmacy_get_qs.store_phone)
            pharmacy_get_qs.store_additional_contact = request.POST.get('store_additional_contact',
                                                                        pharmacy_get_qs.store_additional_contact)
            pharmacy_get_qs.email = request.POST.get('store_additional_contact', pharmacy_get_qs.email)
            pharmacy_get_qs.registration_certificates = request.FILES.get('registration_certificates',
                                                                          pharmacy_get_qs.registration_certificates)
            pharmacy_get_qs.registration_certificates = request.POST.get('is_verified', pharmacy_get_qs.is_verified)
            pharmacy_get_qs.is_phone_verified = request.POST.get('is_phone_verified', pharmacy_get_qs.is_phone_verified)
            pharmacy_get_qs.gst_registration_number = request.POST.get('gst_registration_number',
                                                                       pharmacy_get_qs.gst_registration_number)
            pharmacy_get_qs.date_of_establishment = request.POST.get('date_of_establishment',
                                                                     pharmacy_get_qs.date_of_establishment)
            pharmacy_get_qs.save()
            status = "success"
            message = "Pharmacy Record Updated"

    context_payload = {
        "status": status,
        "message": message,
    }
    return JsonResponse(context_payload)


"""     CLINICS      """


@login_required
def manage_clinic_view(request):
    template = "app_pharma_mg/bui/html/manage_clinic.html"

    profile_get_qs = get_object_or_404(Profile, user=request.user)
    clinic_get_qs = Clinic.objects.all()
    clinic_user_get_qs = ClinicUsers.objects.filter(clinic__in=clinic_get_qs)

    context_payload = {
        "profile_get_qs": profile_get_qs,
        "clinic_user_get_qs": clinic_user_get_qs
    }
    return render(request=request, template_name=template, context=context_payload)


@login_required
def add_clinic(request):
    template = "app_pharma_mg/bui/html/add_clinic.html"

    profile_get_qs = Profile.objects.get(user=request.user)
    if request.method == "POST":
        form = NewClinicRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            form_cleaned_data = form.cleaned_data
            name = form_cleaned_data['name']
            email = form_cleaned_data['email']
            registered_phone = form_cleaned_data['registered_phone']
            additional_contact = form_cleaned_data['additional_contact']
            address = form_cleaned_data['address']
            registration_certificates = form_cleaned_data['registration_certificates']
            is_verified = form_cleaned_data['is_verified']
            is_phone_verified = form_cleaned_data['is_phone_verified']
            gst_registration_number = form_cleaned_data['gst_registration_number']
            type_of_clinic = form_cleaned_data['type_of_clinic']
            date_of_establishment = form_cleaned_data['date_of_establishment']

            clinic_create_qs = Clinic.objects.create(
                added_by=profile_get_qs,
                name=name,
                email=email,
                registered_phone=registered_phone,
                additional_contact=additional_contact,
                address=address,
                registration_certificates=registration_certificates,
                is_verified=is_verified,
                is_phone_verified=is_phone_verified,
                type_of_clinic=type_of_clinic,
                gst_registration_number=gst_registration_number,
                date_of_establishment=date_of_establishment,
            )

            # Owner create for Clinic
            username = f"{name.replace(' ', '_').lower()}__{clinic_create_qs.pk}__owner"
            owner = generate_random_user(username, first_name=f"Clinic_{clinic_create_qs.pk}", last_name="Owner",
                                         email=email, phone=registered_phone)

templates/app_pharma_mg/customer/cart_detail.html
{% extends "app_pharma_mg/customer/home.html" %}
{% load static %}
{% load cart_tag %}

{% block extra_head %}
{% endblock extra_head %}

{% block main_content %}

<section class="h-100 gradient-custom">
    <div class="container py-5">
        <div class="row d-flex justify-content-center my-4">
            <div class="col-md-8">
                <div class="card mb-4">
                    <div class="card-header py-3">
                        <h5 class="mb-0">Cart - {{request.session.cart|length}} items</h5>
                    </div>
                    <div class="card-body">
                        {% for key,value in request.session.cart.items %}
                        <!-- Single item -->
                        <div class="row">
                            <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
                                <!-- Image -->
                                <div class="bg-image hover-overlay hover-zoom ripple rounded"
                                     data-mdb-ripple-color="light">
                                    <img src="{{value.image}}"
                                         class="w-100" alt="{{value.name}}"/>
                                    <a href="#!">
                                        <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                                    </a>
                                </div>
                                <!-- Image -->
                            </div>

                            <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
                                <!-- Data -->
                                <p><strong>{{value.name}}</strong></p>
                                <a href="{% url 'pharmamg:item_clear' value.product_id %}" type="button"
                                   class="btn btn-primary btn-sm me-1 mb-2" data-mdb-toggle="tooltip"
                                   title="Remove item">
                                    <i class="fas fa-trash"></i>
                                </a>
                                <button type="button" class="btn btn-danger btn-sm mb-2" data-mdb-toggle="tooltip"
                                        title="Move to the wish list">
                                    <i class="fas fa-heart"></i>
                                </button>
                                <!-- Data -->
                            </div>

                            <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
                                <!-- Quantity -->
                                <div class="d-flex mb-4" style="max-width: 300px">
                                    <a href="{% url 'pharmamg:item_decrement' value.product_id %}"
                                       class="btn btn-primary px-3 me-2"
                                       onclick="this.parentNode.querySelector('input[type=number]').stepDown() updatePrice();">
                                        <i class="fas fa-minus"></i>
                                    </a>

                                    <div class="form-outline">
                                        <input min="1" name="quantity" value="{{value.quantity}}" readonly type="number"
                                               class="form-control"/>
                                    </div>

                                    <a href="{% url 'pharmamg:item_increment' value.product_id %}"
                                       class="btn btn-primary px-3 ms-2"
                                       onclick="this.parentNode.querySelector('input[type=number]').stepUp(); updatePrice();">
                                        <i class="fas fa-plus"></i>
                                    </a>
                                </div>
                                <!-- Quantity -->

                                <!-- Price -->
                                <p class="text-start text-md-center">
                                    <strong>Rs. {{ value.price|multiply:value.quantity }}</strong>
                                </p>
                                <!-- Price -->
                            </div>
                        </div>
                        <!-- Single item -->
                        <hr class="my-4"/>
                        {% endfor %}
                    </div>
                </div>

                <div class="card mb-4">
                    <div class="card-body">
                        <p><strong>Expected shipping delivery</strong></p>
                        <p class="mb-0">15.06.2023 - 20.06.2023</p>
                    </div>
                </div>
                <div class="card mb-4 mb-lg-0">
                    <div class="card-body">
                        <p><strong>We accept</strong></p>
                        <img class="me-2" width="45px"
                             src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
                             alt="Visa"/>
                        <img class="me-2" width="45px"
                             src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
                             alt="American Express"/>
                        <img class="me-2" width="45px"
                             src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
                             alt="Mastercard"/>
                        <img class="me-2" width="45px"
                             src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce/includes/gateways/paypal/assets/images/paypal.webp"
                             alt="PayPal acceptance mark"/>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4">
                    <div class="card-header py-3">
                        <h5 class="mb-0">Summary</h5>
                    </div>
                    <div class="card-body">
                        <ul class="list-group list-group-flush">
                            <li
                                    class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                                Products
                                <span>Rs. {{total}}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                                Shipping
                                <span>Rs. 20</span>
                            </li>
                            <li
                                    class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                                <div>
                                    <strong>Total amount</strong>
                                    <strong>
                                        <p class="mb-0">(including VAT)</p>
                                    </strong>
                                </div>
                                <span id="total_price_vat"><strong>Rs. {{total}}</strong></span>
                            </li>
                        </ul>

                        <a type="button" class="btn btn-primary btn-lg btn-block" href="{% url 'pharmamg:checkout' %}">
                            Go to checkout
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock main_content %}


{% block extra_javascript %}
<script type="text/javascript">
</script>
{% endblock extra_javascript %}

templates/app_pharma_mg/customer/home.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<!-- Font Awesome -->
<link
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        rel="stylesheet"
/>
<!-- Google Fonts -->
<link
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        rel="stylesheet"
/>
<!-- MDB -->
<link
        href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.1/mdb.min.css"
        rel="stylesheet"
/>
<!-- MDB -->
<script
        type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.1/mdb.min.js"
></script>
{% block extra_head %}
{% endblock extra_head %}
{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pharmamg:patient_home' %}">
            <img src="{% static 'website/favicon/favicon.png' %}" height="28" alt="Pharma MG">
            Pharma MG
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'pharmamg:patient_home' %}">Buy
                        Medicines</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Book Appointment</a>
                </li>
                <li class="nav-item ms-auto">
                    <a class="nav-link justify-content-end" href="{% url 'pharmamg:cart_detail' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-cart3" viewBox="0 0 16 16">
                            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                        </svg>
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                             class="bi bi-person-fill" viewBox="0 0 16 16">
                            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
                        </svg>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <span class="fs-6 px-1">Mobile: {{profile_get_qs.phone}} </span>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'pharmamg:order_detail' %}">Orders</a></li>
                        <li><a class="dropdown-item" href="#">Consultations</a></li>
                        <li><a class="dropdown-item" href="{% url 'patient_logout' %}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>


{% block main_content %}
{% endblock main_content %}


<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-muted">© 2023 Pharma MG</p>

    <a href="{% url 'pharmamg:patient_home' %}"
       class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
        <img src="{% static 'website/favicon/favicon.png' %}" height="28" alt="Pharma MG">
    </a>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
        <li class="ms-3"><a class="text-muted" href="#">
            <svg class="bi" width="24" height="24">
                <use xlink:href="#twitter"></use>
            </svg>
        </a></li>
        <li class="ms-3"><a class="text-muted" href="#">
            <svg class="bi" width="24" height="24">
                <use xlink:href="#instagram"></use>
            </svg>
        </a></li>
        <li class="ms-3"><a class="text-muted" href="#">
            <svg class="bi" width="24" height="24">
                <use xlink:href="#facebook"></use>
            </svg>
        </a></li>
    </ul>
</footer>

{% endblock %}

{% block javascript %}
{% block extra_javascript %}
{% endblock extra_javascript %}
{% endblock %}

templates/app_pharma_mg/customer/product_view.html
{% extends "app_pharma_mg/customer/home.html" %}
{% load static %}

{% block extra_head %}
<style>
.card{

border:1px solid #eee;
cursor: pointer;
}


.weight{

margin-top: -65px;
transition: all 0.5s;
}

.weight small{

color: #e2dede;
}

.buttons {
    padding: 10px;
background-color: #d6d4d44f;
border-radius: 4px;
position: relative;
margin-top: 7px;
opacity: 0;
transition: all 0.8s;
}


.cart-button {
    height: 48px
}

.cart-button:focus {
    box-shadow: none
}


@keyframes item {
    0% {
        opacity: 1;
        top: 30%;
        left: 30%
    }

    25% {
        opacity: 1;
        left: 26%;
        top: 0%
    }

    50% {
        opacity: 1;
        left: 23%;
        top: -22%
    }

    75% {
        opacity: 1;
        left: 19%;
        top: -18%
    }

    100% {
        opacity: 1;
        left: 14%;
        top: 28%
    }
}



.card:hover .buttons{

    opacity: 1;
}


.card:hover .weight{

     margin-top: 10px;
}

.card:hover{

    transform: scale(1.04);
    z-index: 2;
    overflow: hidden;
}

</style>
{% endblock extra_head %}

{% block main_content %}
<div class="container my-3">
    <div class="row">
        <div class="col-md-12">
            <input class="filter" placeholder="Search Products"/>
        </div>
    </div>
</div>

<div class="container">
    <div class="row g-1">
        {% for product in product_get_qs %}
        <div class="col-md-3 mx-2 my-3">
            <div class="card p-3 text-center" data-string="{{product.item_name}}">
                <div class="text-center">
                    <img src="{{product.item_image.url}}" width="200">
                </div>
                <div class="product-details">
                    <span class="font-weight-bold d-block">Rs. {{product.item_price}}</span>
                    <span>{{product.item_name}}  {{product.item_dose}}</span>
                    <span>Brand <u>{{product.item_brand}}</u></span>
                    <span>Brand <u>{{product.item_manufacturer}}</u></span>
                    <div class="buttons d-flex flex-row">
                        <a href="{% url 'pharmamg:cart_add' id=product.item_id %}"
                           class="btn btn-success w-100 cart-button btn-block">Add to cart</a>
                    </div>

                    <div class="weight text-truncate">
                        <small>{{product.item_information}}</small>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock main_content %}


{% block extra_javascript %}

<script type="text/javascript">
$(".filter").on("keyup", function() {
  var input = $(this).val().toUpperCase();

  $(".card").each(function() {
    if ($(this).data("string").toUpperCase().indexOf(input) < 0) {
      $(this).hide();
    } else {
      $(this).show();
    }
  })
});


</script>

{% endblock extra_javascript %}