PharmaMG/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from app_account.views import home_view, business_login, business_logout, register_user_ajax, \
    patient_login, patient_logout

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home_view, name="home"),
    path('bui_login/', business_login, name="bui_login"),
    path('bui_logout/', business_logout, name="bui_logout"),

    path('register_user_ajax/', register_user_ajax, name="send_otp"),
    path('patient_login/', patient_login, name="patient_login"),
    path('patient_logout/', patient_logout, name="patient_logout"),

    path('pharma-mg/', include(('app_pharma_mg.urls', 'app_pharma_mg'), namespace='pharmamg')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_pharma_mg/urls.py
from django.urls import path

from app_pharma_mg import cart_views
from app_pharma_mg.cart_views import order_detail
from app_pharma_mg.views import *

urlpatterns = [
    # BUI urls
    path('bui_dashboard/', dashboard_view, name="dashboard"),

    # pharmacy urls for admin user
    path('bui_manage_pharmacy/', manage_pharmacy_view, name="manage_pharmacy"),
    path('bui_add_pharmacy/', add_pharmacy, name="add_pharmacy"),
    path('edit_form_ajax/', edit_form_ajax, name="edit_form_ajax"),
    path('bui_delete_pharmacy/<str:pharmacy_id>/', delete_pharmacy_ajax, name="delete_pharmacy"),

    # clinic urls for admin user
    path('bui_manage_clinic/', manage_clinic_view, name="manage_clinic"),
    path('bui_add_clinic/', add_clinic, name="add_clinic"),
    path('edit_clinic_form_ajax/', edit_form_ajax, name="edit_clinic_form_ajax"),
    path('bui_delete_clinic/<str:clinic_id>/', delete_pharmacy_ajax, name="delete_clinic"),

    # PHARMACY USER urls
    path('bui_pharmacy_dashboard/', dashboard_pharmacy_view, name="pharmacy_dashboard"),
    path('bui_pharmacy_users/', manage_pharmacy_user_view, name="manage_pharmacy_users"),
    path('bui_pharmacy_users_delete/<str:user_id>/', delete_pharmacy_employee_ajax, name="delete_pharmacy_employee"),
    path('bui_add_pharmacy_user/', add_pharmacy_employee, name="add_pharmacy_employee"),
    path('bui_pharmacy_products/', manage_pharmacy_products_view, name="manage_pharmacy_products"),
    path('bui_pharmacy_edit_product_form_ajax/', edit_product_form_ajax, name="edit_product_form_ajax"),
    path('bui_add_pharmacy_product/', add_pharmacy_product, name="add_pharmacy_product"),
    path('bui_create_order_pharmacy_view/', create_order_pharmacy_view, name="create_order_pharmacy_view"),
    path('bui_create_order_ajax/', create_order_ajax, name="create_order_ajax"),
    path('bui_manage_pharmacy_orders_view/', manage_pharmacy_orders_view, name="manage_pharmacy_orders_view"),

    # CLINIC USER urls
    path('bui_clinic_dashboard/', dashboard_clinic_view, name="clinic_dashboard"),
    path('bui_clinic_users/', manage_clinic_user_view, name="manage_clinic_users"),
    path('bui_clinic_users_delete/<str:user_id>/', delete_clinic_employee_ajax, name="delete_clinic_employee"),
    path('bui_add_clinic_user/', add_clinic_employee, name="add_clinic_employee"),
    path('bui_schedule_consultation_view/', schedule_consultation_view, name="schedule_consultation_view"),
    path('bui_schedule_consultation_ajax/', schedule_consultation_ajax, name="schedule_consultation_ajax"),
    path('bui_manage_consultation_view/', manage_consultation_view, name="manage_consultation_view"),

    # PATIENT/CUSTOMER urls
    path('patient_home/', patient_home, name="patient_home"),
    path('order_detail/', order_detail, name="order_detail"),

    # CART URLS
    path('cart/add/<str:id>/', cart_views.cart_add, name='cart_add'),
    path('cart/item_clear/<str:id>/', cart_views.item_clear, name='item_clear'),
    path('cart/item_increment/<str:id>/',
         cart_views.item_increment, name='item_increment'),
    path('cart/item_decrement/<str:id>/',
         cart_views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', cart_views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/', cart_views.cart_detail, name='cart_detail'),
    path('cart/checkout/', cart_views.checkout, name='checkout'),

]

app_account/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models

ROLES = (
    ('admin', 'ADMIN'),
    ('patient', 'PATIENT'),
    ('doctor', 'DOCTOR'),
    ('pharmacist', 'PHARMACIST'),
    ('receptionist', 'RECIPTIONIST')
)


class Profile(models.Model):
    profile_id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(blank=True, null=True, choices=ROLES, max_length=100)

    phone = models.CharField(blank=True, null=True, max_length=15)
    email = models.CharField(blank=True, null=True, max_length=200)

    first_name = models.CharField(blank=True, null=True, max_length=200)
    last_name = models.CharField(blank=True, null=True, max_length=200)
    user_address = models.TextField(blank=True, null=True)

    is_mobile_verified = models.BooleanField(default=False)

    profile_pic = models.FileField(blank=True, null=True, upload_to="app_pharmamg/profile_images/")

    updated_on = models.DateTimeField(auto_now=True)
    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_time',)

    def __str__(self):
        return f"{self.profile_id}"


class OtpVerify(models.Model):
    otp_sid = models.CharField(primary_key=True, default="", max_length=200)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)

    status = models.CharField(blank=True, null=True, max_length=100)
    otp = models.CharField(blank=True, null=True, max_length=10)
    is_verified = models.BooleanField(default=False)
    has_expired = models.BooleanField(default=False)

    updated_on = models.DateTimeField(auto_now=True)
    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_time',)

    def __str__(self):
        return f"{self.otp_sid}"


class Address(models.Model):
    address_id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    address_line_1 = models.TextField(blank=True, null=True)
    address_line_2 = models.TextField(blank=True, null=True)
    city = models.CharField(blank=True, null=True, max_length=200)
    state = models.CharField(blank=True, null=True, max_length=200)
    country = models.CharField(blank=True, null=True, default="INDIA", max_length=200)
    pincode = models.CharField(blank=True, null=True, max_length=20)

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    updated_on = models.DateTimeField(auto_now=True)
    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_time',)

    def __str__(self):
        return f"{self.address_id}"

app_pharma_mg/models.py
import uuid

from django.db import models

from app_account.models import Profile

TIMINGS = (
    ('9-6', (
        ('9-10', '9 am to 10 am'),
        ('10-11', '10 am to 11 am'),
        ('11-12', '11 am to 12 pm'),
        ('12-13', '12 pm to 1 pm'),
        ('14-15', '2 pm to 3 pm'),
        ('14-15', '2 pm to 3 pm'),
        ('15-16', '3 pm to 4 pm'),
        ('16-17', '4 pm to 5 pm'),
    )),
    ('9-8', (
        ('9-10', '9 am to 10 am'),
        ('10-11', '10 am to 11 am'),
        ('11-12', '11 am to 12 pm'),
        ('12-13', '12 pm to 1 pm'),
        ('14-15', '2 pm to 3 pm'),
        ('14-15', '2 pm to 3 pm'),
        ('15-16', '3 pm to 4 pm'),
        ('16-17', '4 pm to 5 pm'),
        ('17-18', '5 pm to 6 pm'),
    )),
    ('12-8', (
        ('12-13', '12 pm to 1 pm'),
        ('14-15', '2 pm to 3 pm'),
        ('14-15', '2 pm to 3 pm'),
        ('15-16', '3 pm to 4 pm'),
        ('16-17', '4 pm to 5 pm'),
        ('17-18', '5 pm to 6 pm'),
    )),
    ('12-10', (
        ('12-13', '12 pm to 1 pm'),
        ('14-15', '2 pm to 3 pm'),
        ('14-15', '2 pm to 3 pm'),
        ('15-16', '3 pm to 4 pm'),
        ('16-17', '4 pm to 5 pm'),
        ('17-18', '5 pm to 6 pm'),
        ('18-19', '6 pm to 7 pm'),
        ('19-20', '7 pm to 8 pm'),
        ('20-21', '8 pm to 9 pm'),
    )),
)


class Pharmacy(models.Model):
    pid = models.UUIDField(primary_key=True, default=uuid.uuid4)
    added_by = models.ForeignKey(Profile, on_delete=models.CASCADE)

    name = models.CharField(blank=True, null=True, max_length=200)
    address = models.TextField(blank=True, null=True)

    store_phone = models.CharField(blank=True, null=True, max_length=15)
    store_additional_contact = models.CharField(blank=True, null=True, max_length=15)
    email = models.CharField(blank=True, null=True, max_length=200)

    registration_certificates = models.FileField(blank=True, null=True)

    is_verified = models.BooleanField(default=False)
    is_phone_verified = models.BooleanField(default=False)

    gst_registration_number = models.CharField(blank=True, null=True, max_length=150)

    date_of_establishment = models.DateField(blank=True, null=True)

    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_time',)

    def __str__(self):
        return f"{self.pid}"


class PharmacyUsers(models.Model):
    USERS = (
        ('owner', 'Store Owner'),
        ('pharmacist', 'Pharmacist'),
    )

    pharmacy_user_id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.OneToOneField(Profile, on_delete=models.CASCADE)

    pharmacy = models.ForeignKey(Pharmacy, on_delete=models.CASCADE, blank=True, null=True)

    role = models.CharField(blank=True, null=True, choices=USERS, max_length=200)

    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_time',)

    def __str__(self):
        return f"{self.pharmacy_user_id}"


class Clinic(models.Model):
    TIMINGS = (
        ('9-6', '9 am to 6 pm'),
        ('9-8', '9 am to 8 pm'),
        ('12-8', '12 am to 8 pm'),
        ('12-10', '12 am to 10 pm'),
    )

    cid = models.UUIDField(primary_key=True, default=uuid.uuid4)
    added_by = models.ForeignKey(Profile, on_delete=models.CASCADE)

    name = models.CharField(blank=True, null=True, max_length=200)
    address = models.TextField(blank=True, null=True)

    type_of_clinic = models.CharField(blank=True, null=True, max_length=100)
    clinic_timing = models.CharField(blank=True, null=True, max_length=100, choices=TIMINGS)

    registered_phone = models.CharField(blank=True, null=True, max_length=15)
    additional_contact = models.CharField(blank=True, null=True, max_length=15)
    email = models.CharField(blank=True, null=True, max_length=200)

    registration_certificates = models.FileField(blank=True, null=True)

    is_verified = models.BooleanField(default=False)
    is_phone_verified = models.BooleanField(default=False)

    gst_registration_number = models.CharField(blank=True, null=True, max_length=150)

    date_of_establishment = models.DateField(blank=True, null=True)

    updated_on = models.DateTimeField(auto_now=True)
    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_time',)

    def __str__(self):
        return f"{self.cid}"


class ClinicUsers(models.Model):
    USERS = (
        ('doctor', 'Doctor'),
        ('reciptionist', 'Reciptionist'),
    )

    clinic_user_id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.OneToOneField(Profile, on_delete=models.CASCADE)

    clinic = models.ForeignKey(Clinic, on_delete=models.CASCADE, blank=True, null=True)
    specialization = models.CharField(blank=True, null=True, max_length=200)

    role = models.CharField(blank=True, null=True, choices=USERS, max_length=200)

    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_time',)

    def __str__(self):
        return f"{self.clinic_user_id}"


def product_id_create():
    return "PR_" + uuid.uuid4()


class Item(models.Model):
    CATEGORY = (
        ('drugs', 'DRUG'),
        ('antibiotic', 'ANIT-BIOTICS'),
        ('syrup', 'SYRUP'),
        ('allopathy', 'ALLOPATHY'),
        ('homeopathy', 'HOMEOPATHY'),
        ('vitamins_supplements', 'VITAMINS and SUPPLEMENTS'),
        ('personal_care', 'PERSONAL CARE'),
        ('protein', 'PROTEIN SUPPLEMENTS'),
    )

    item_id = models.CharField(primary_key=True, default=product_id_create, max_length=200)
    pharmacy = models.ForeignKey(Pharmacy, on_delete=models.CASCADE, blank=True, null=True)

    item_name = models.CharField(blank=True, null=True, max_length=200)
    item_category = models.CharField(blank=True, null=True, choices=CATEGORY, max_length=200)
    item_price = models.FloatField(blank=True, null=True)
    item_stock = models.IntegerField(blank=True, null=True)
    item_composition = models.CharField(blank=True, null=True, max_length=200)
    item_dose = models.CharField(blank=True, null=True, max_length=200)
    item_uses = models.TextField(blank=True, null=True)
    item_side_effects = models.TextField(blank=True, null=True)

    item_brand = models.CharField(blank=True, null=True, max_length=200)
    item_manufacturer = models.CharField(blank=True, null=True, max_length=200)
    item_information = models.TextField(blank=True, null=True)

    item_image = models.FileField(blank=True, null=True)

    is_prescription_required = models.BooleanField(default=False)

    updated_on = models.DateTimeField(auto_now=True)
    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_time', '-updated_on')

    def __str__(self):
        return f"{self.item_name}"


class Prescription(models.Model):
    prescription_id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    added_by = models.ForeignKey(Profile, on_delete=models.CASCADE)

    prescription_name = models.CharField(blank=True, null=True, max_length=200)
    prescribed_by = models.CharField(blank=True, null=True, max_length=200)

    prescription = models.FileField(blank=True, null=True)

    order_updated_on = models.DateTimeField(auto_now=True)
    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_time', '-order_updated_on')

    def __str__(self):
        return f"{self.prescription_name}"


class Transaction(models.Model):
    STATUS = (
        ('success', 'SUCCESS'),
        ('incomplete', 'ON HOLD'),
        ('failed', 'FAILED'),
        ('rollbacked', 'ROLLBACKED'),
    )

    transaction_id = models.UUIDField(primary_key=True, default=uuid.uuid4)

    transaction_status = models.CharField(blank=True, null=True, choices=STATUS, max_length=50)
    transaction_mode = models.CharField(blank=True, null=True, max_length=50)

    order_updated_on = models.DateTimeField(auto_now=True)
    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_time', '-order_updated_on')

    def __str__(self):
        return f"{self.transaction_id}"


class Order(models.Model):
    MODE = (
        ('online', 'ONLINE'),
        ('offline', 'STORE POS'),
        ('oncall', 'ON CALL ORDER'),
    )

    STATUS = (
        ('placed', 'ORDER PLACED'),
        ('packed', 'ORDER PACKED'),
        ('delivery', 'OUT FOR DELIVERY'),
        ('delivered', 'DELIVERED'),
    )

    order_id = models.UUIDField(primary_key=True, default=uuid.uuid4)

    placed_by = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, null=True)
    store = models.ForeignKey(Pharmacy, on_delete=models.CASCADE, blank=True, null=True)
    item = models.ManyToManyField(Item, blank=True)
    transaction = models.OneToOneField(Transaction, on_delete=models.CASCADE, blank=True, null=True)

    prescription = models.ManyToManyField(Prescription, blank=True)

    total_amount = models.FloatField(blank=True, null=True)

    mode = models.CharField(blank=True, null=True, choices=MODE, default="offline", max_length=100)
    order_status = models.CharField(blank=True, null=True, choices=STATUS, max_length=100)

    order_updated_on = models.DateTimeField(auto_now=True)
    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_time', '-order_updated_on')

    def __str__(self):
        return f"{self.order_id}"


class Consultation(models.Model):
    MODE = (
        ('online', 'ONLINE'),
        ('offline', 'CLINIC VISIT'),
        ('oncall', 'ON CALL'),
    )

    STATUS = (
        ('canceled', 'CANCELED'),
        ('rescheduled', 'RESCHUDLED'),
        ('booked', 'BOOKED'),
        ('ongoing', 'ONGOING'),
        ('completed', 'COMPLETED'),
    )

    consultation_id = models.UUIDField(primary_key=True, default=uuid.uuid4)

    placed_by = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, null=True)

templates/app_pharma_mg/bui/html/dashboard.html
{% extends "app_pharma_mg/bui/html/main.html" %}
{% load static %}

{% block main_block %}
<h1 class="mt-4">Dashboard</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Dashboard</li>
</ol>
<div class="row">
    <div class="col-xl-6 col-md-6">
        <div class="card bg-white text-dark mb-4 text-center">
            <div class="card-body fw-bold lh-sm">
                <span class="fs-1">{{pharmacy_get_qs|length}}</span>
                <hr class="dropdown-divider"/>
                Pharmacies Registered
            </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-dark stretched-link" href="{% url 'pharmamg:manage_pharmacy' %}">Manage</a>
                <div class="small text-dark"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-6 col-md-6">
        <div class="card bg-white text-dark mb-4 text-center">
            <div class="card-body fw-bold lh-sm">
                <span class="fs-1">{{clinic_get_qs|length}}</span>
                <hr class="dropdown-divider"/>
                Clinics Registered
            </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-dark stretched-link" href="pharmamg:manage_clinic">Manage</a>
                <div class="small text-dark"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/app_pharma_mg/bui/html/main.html
{% extends "base.html" %}
{% load static %}

{% block title %}Pharma MG{% endblock %}

{% block head %}
<style>{% include 'app_pharma_mg/bui/css/main.css' %}</style>
{% endblock %}


{% block content %}

<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    {% if profile_get_qs.role == 'admin' %}
    <a class="navbar-brand ps-3" href="{% url 'pharmamg:dashboard' %}">{{profile_get_qs.role|title}} Dashboard</a>
    {% elif profile_get_qs.role == 'pharmacist' %}
    <a class="navbar-brand ps-3" href="{% url 'pharmamg:pharmacy_dashboard' %}">{{profile_get_qs.role|title}}
        Dashboard</a>
    {% elif profile_get_qs.role == 'doctor' %}
    <a class="navbar-brand ps-3" href="{% url 'pharmamg:clinic_dashboard' %}">{{profile_get_qs.role|title}}
        Dashboard</a>
    {% elif profile_get_qs.role == 'reciptionist' %}
    <a class="navbar-brand ps-3" href="{% url 'pharmamg:clinic_dashboard' %}">{{profile_get_qs.role|title}}
        Dashboard</a>
    {% endif %}
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i
            class="fas fa-bars"></i></button>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown"
               aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#!">Profile</a></li>
                <li>
                    <hr class="dropdown-divider"/>
                </li>
                <li><a class="dropdown-item" href="{% url 'bui_logout' %}">Logout</a></li>
            </ul>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    {% if profile_get_qs.role == 'admin' %}
                    <div class="sb-sidenav-menu-heading">Home</div>
                    <a class="nav-link" href="{% url 'pharmamg:dashboard' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Dashboard
                    </a>
                    <div class="sb-sidenav-menu-heading">Pharmacy</div>
                    <a class="nav-link" href="{% url 'pharmamg:add_pharmacy' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-user-plus"></i></div>
                        Add Pharmacy
                    </a>
                    <a class="nav-link" href="{% url 'pharmamg:manage_pharmacy' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                        Manage Pharmacy
                    </a>
                    <div class="sb-sidenav-menu-heading">Clinic</div>
                    <a class="nav-link" href="{% url 'pharmamg:add_clinic' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-user-plus"></i></div>
                        Add Clinic
                    </a>
                    <a class="nav-link" href="{% url 'pharmamg:manage_clinic' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                        Manage Clinic
                    </a>
                    {% elif profile_get_qs.role == 'pharmacist' %}
                    <div class="sb-sidenav-menu-heading">Home</div>
                    <a class="nav-link" href="{% url 'pharmamg:pharmacy_dashboard' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Dashboard
                    </a>
                    {% if pharmacy_user_get_qs.role == 'owner' %}
                    <a class="nav-link" href="{% url 'pharmamg:add_pharmacy_employee' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-user-plus"></i></div>
                        Add User
                    </a>
                    <a class="nav-link" href="{% url 'pharmamg:manage_pharmacy_users' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                        Manage User
                    </a>
                    {% endif %}
                    <div class="sb-sidenav-menu-heading">Orders</div>
                    <a class="nav-link" href="{% url 'pharmamg:create_order_pharmacy_view' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-user-plus"></i></div>
                        Create Order
                    </a>
                    <a class="nav-link" href="{% url 'pharmamg:manage_pharmacy_orders_view' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                        Manage Orders
                    </a>
                    <div class="sb-sidenav-menu-heading">Items</div>
                    <a class="nav-link" href="{% url 'pharmamg:add_pharmacy_product' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-user-plus"></i></div>
                        Add New Item
                    </a>
                    <a class="nav-link" href="{% url 'pharmamg:manage_pharmacy_products' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                        Manage Items
                    </a>
                    {% elif profile_get_qs.role == 'doctor' or profile_get_qs.role == 'receptionist' %}
                    <div class="sb-sidenav-menu-heading">Home</div>
                    <a class="nav-link" href="{% url 'pharmamg:clinic_dashboard' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Dashboard
                    </a>
                    {% if clinic_user_get_qs.role == 'doctor' %}
                    <a class="nav-link" href="{% url 'pharmamg:add_clinic_employee' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-user-plus"></i></div>
                        Add User
                    </a>
                    <a class="nav-link" href="{% url 'pharmamg:manage_clinic_users' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                        Manage User
                    </a>
                    {% endif %}
                    <div class="sb-sidenav-menu-heading">Consultations</div>
                    <a class="nav-link" href="{% url 'pharmamg:schedule_consultation_view' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-user-plus"></i></div>
                        New Appointment
                    </a>
                    <a class="nav-link" href="{% url 'pharmamg:manage_consultation_view' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                        Manage Appointments
                    </a>
                    {% endif %}
                </div>
            </div>
            <div class="sb-sidenav-footer">
                <div class="small">Logged in user:</div>
                {{profile_get_qs.first_name|title}} {{profile_get_qs.last_name|title}}
            </div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4 py-4">
                {% include 'snippets/alerts/alert.html' %}
                {% block main_block %}
                {% endblock %}
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; PharmaMG 2023</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</div>

{% endblock %}

{% block javascript %}
<script type="text/javascript">
    {% include 'app_pharma_mg/bui/js/main.js' %}
    {% block extra_js %}
    {% endblock %}

</script>
{% endblock %}